### ISSUE TITLE
Save generator and load it only for prediction

### ISSUE THREAD

**Issue by agelosk** [lab-ml/nn#1]
Hello,

Thank you for your implementation of cycle gans, it is very clear. I would like to ask if there is a way to save the generators every 500 iterations (exactly when they predict the test images) so I can load them in a different moment and only perform prediction in a specific test set with the loaded model (in a new code, independent of cycle_gan.py)

Thank you,
Agelos

**Comment by vpj** [comment]
Hi,

You can save checkpoints with `experiment.save_checkpoint` . It will save all the models added to the experiment as dictionary with `experiment.add_pytorch_models`.

When starting a new experiment you can load specified models with `experiment.load_models`. Note that the model names should match between the experiment used to save models and load models.

Documentation links
* [save_checkpoint](http://lab-ml.com/api/experiment.html#labml.experiment.save_checkpoint)
* [add_pytorch_models](http://lab-ml.com/api/experiment.html#labml.experiment.add_pytorch_models)
* [load_models](http://lab-ml.com/api/experiment.html#labml.experiment.load_models)

Join our slack channel for discussions: https://join.slack.com/t/labforml/shared_invite/zt-egj9zvq9-Dl3hhZqobexgT7aVKnD14g/

**Comment by vpj** [comment]
https://github.com/lab-ml/nn/compare/18c96c56922a...98b659f4396b

@agelosk this commit does saving and loading of checkpoints. Hope it helps you
