### ISSUE TITLE
pylit implementation?

### ISSUE THREAD

**Issue by pseeth** [lab-ml/nn#3]
Hello,

Very nice job on this site, I really love the side-by-side code. I was hoping to do something similar for my own documentation and was hoping you could point me to what you used to create these pages. I see something called `pylit` in a Makefile, along with a link to your own templates for it, but it doesn't appear to be anywhere else under the lab-ml organization.

Thanks very much!

**Comment by vpj** [comment]
Hi,

It's a script I wrote. It's kind of messy and not well maintained. I'm planning to cleanup and open source when I get some free time.

I wrote and published an interactive version of it that I thought more people will find useful. [https://github.com/vpj/annotate](https://github.com/vpj/annotate)

See if it helps you.

**Comment by pseeth** [comment]
Gotcha, thanks for the link! Do let me know when you've open sourced what you have, looking forward to using it!

**Comment by Ryu1845** [comment]
@vpj Any updates on this?
