### ISSUE TITLE
The inference speed of Switch Transformer

### ISSUE THREAD

**Issue by kugwzk** [lab-ml/nn#33]
Thanks for a nice implementation of Switch Transformer here [https://nn.labml.ai/transformers/switch/](url).
In the original paper, the speed is slower than T5-BASE but they used much einsum in code. I see you choose index operation to handle different experts. I have a question about how this implementation speed compares to the original Transformer (not using switch layer).

**Comment by vpj** [comment]
The original paper uses a distributed implementation where each expert was running on its own device (GPU). Our implementation has all the experts on a single device. It's slower than a transformer without a switch layer, but has more parameters. It's faster than the original transformer with the same number of parameters.

**Comment by kugwzk** [comment]
Thanks~ BTW, in the original paper although they use separate devices for different experts, Switch Transformer is also slower than original Transformer.
