### ISSUE TITLE
Feature Request: GPT-2

### ISSUE THREAD

**Issue by loretoparisi** [lab-ml/nn#4]
Thanks for this repo! Code descriptions are well written and code is clear!
It would be worth to provide an implementation of OpenAI [GPT-2](https://openai.com/blog/better-language-models/)

Thanks.

**Comment by vpj** [comment]
Yeah that sounds interesting. Will work on that next when we get time.

**Comment by vpj** [comment]
https://lab-ml.com/labml_nn/transformers/gpt/ it reuses the transformer implementation so wasn't hard to write. Most of the time was spent on debugging because I accidentally was not using decouple weight decay.

**Comment by loretoparisi** [comment]
@vpj cool! thank you. 💯
